---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 27/12/2022 00:58
---

return {
    {
        header = "Programming",
        lines = {
            {"Game", "Nino van Hooff"},
            {"Settings", "Matt Septhon"}
        }
    },
    {
        header = "Art",
        lines = {
            "Mike Brown",
            "Count Moriarty",
            "Richard Lems",
            "Casey Gatti"
        }
    },
    {
        header = "Script",
        lines = {
            "Magnum Kramer"
        }
    },
    {
        header = "Starring",
        lines = {
            {"CEO", "Jodi Hutton"},
            {"Launch Director", "Gary Williams"}
        }
    },
    {
        header = "Audio",
        lines = {
            "Arjan Terpstra",
            "Freesound.org"
        }
    },
    {
        header = "Music",
        lines = {
            {"Escape", "Aries Beats" },
            {"AUTO", "Danya Vodovoz" },
            {"Upbeat", "Aries Beats" },
            {"Home Stretch", "Gunnar Olsen" },
            {"RefractiveDX", "@Choosh" },
            {"Strange Stuff", "Matt Harris" },
            {"Smooth and Cool", "Nico Staf" },
            {"The Countdown", "Aries Beats" },
        }
    },
    {
        header = "Testers",
        lines = {
            "@Guv__Bubbs - @professir - @Rebecca - @fast83"
        }
    },
    {
        header = "Thanks",
        lines = {
            "Matt Septhon",
            "James Daniels", -- helped get me the playdate
            "@Labeardi" -- Concept Art
        }
    }
}
