---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 05/08/2022 10:30
---

class('CamController').extends()

local abs <const> = math.abs
local maxHistoryLength <const> = 8
local integralThreshold <const> = maxHistoryLength * 25
local speedStep <const> = 2

function CamController:init()
    self.speed = 0
    self.history = {}
    self.errorIntegral = 0
end

--- returns new value based on value and target
function CamController:update(value, target)
    local error = target - value
    table.insert(self.history, error)
    self.errorIntegral = self.errorIntegral + error
    if #self.history > maxHistoryLength then
        self.errorIntegral = self.errorIntegral - table.remove(self.history, 1)
    end

    if abs(self.errorIntegral) > integralThreshold then
        self.speed = self.speed + sign(self.errorIntegral) * speedStep
        self.errorIntegral = 0
    end

    return value + self.speed
end
