---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 13/03/2022 00:13
---

local random <const> = math.random
local thrust_sound <const> = thrust_sound
local getButtonState <const> = playdate.getButtonState
local buttonState = 0

local inputManager = inputManager
local throttle <const> = Input.actionThrottle
local selfRight <const> = Input.actionSelfRight

local sinThrustT <const> = sinThrustT
local cosThrustT <const> = cosThrustT

function ProcessInputs()
    buttonState = getButtonState()
    -- thrust
    if (inputManager:isInputPressed(throttle) and fuel > 0) then
        if Sounds and thrust == 0 then thrust_sound:play(0, 0.98 + random() * 0.04) end
        thrust = 1
        if not Debug then
            fuel = fuel - burnRate
        end
        fuelSpent = fuelSpent + burnRate/10
        if not flying then
            vx = 0
            vy = 0
        end
        flying = true
        vx = vx + cosThrustT[planeRot]*(thrustPower+extras[1]*turboPower)
        vy = vy - sinThrustT[planeRot]*(thrustPower+extras[1]*turboPower)
    elseif thrust == 1 then
        if Sounds then thrust_sound:stop() end
        thrust = 0
    end

    -- rotation
    local rotationInput = inputManager:rotationInput(planeRot)
    if rotationInput and flying and not steeringDisabled then
        planeRot = rotationInput
    elseif inputManager:isInputPressed(selfRight) then
            if planeRot~=18 then
                if planeRot>18 or planeRot<6 then
                    planeRot = planeRot-1
                else
                    planeRot = planeRot+1
                end
            end
            if planeRot<0 then planeRot = 23 end
            inputManager:resetRotationTimeout()
    else
        inputManager:resetRotationTimeout()
    end
end

function isThrottleJustPressed()
    return inputManager:isInputJustPressed(throttle)
end
