---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 11/03/2022 16:29
---

local file <const> = playdate.file
local unpack <const> = string.unpack
local luaMod <const> = luaMod


function LoadFile(path)
    printf("loading ".. path)

    levelT, brickT, specialT, levelProps = nil, nil, nil

    local levelT
    sample("pdz load", function() levelT = file.run(path) end, 1)
    levelProps = levelT["levelProps"]
    levelProps.lives = levelProps.lives or 9
    specialT = levelT["specialT"]
    brickT = {}
    local format = levelProps.packFormat
    local packSize = string.packsize(format)
    local packSizeOffset = packSize-1

    local unpackMeta = {
        __index = function(tbl, idx)
            -- tbl["compressed"] contains the packed string.
            -- idx*5-4: each tile entry is 5 bytes long,
            -- for idx 1 we should start reading at pos 1. So, 1*packSize-packSizeOffset = 1
            return {unpack(format, tbl["compressed"], idx*packSize-packSizeOffset)}
        end
    }

    local brickFile = file.open(path..".bin")
    for x = 1, levelProps.sizeX do
        brickT[x]= setmetatable({compressed = brickFile:read(5*levelProps.sizeY)}, unpackMeta)
    end


    printf("loaded dim",#brickT,#brickT[1])
    printf("loaded #specials:", #specialT)

    return true
end

function levelNumString(levelNumber)
    return string.format("%02d", levelNumber)
end

function levelPath(_levelNumber)
    local levelNumber = _levelNumber or currentLevel
    return "levels/LEVEL" .. levelNumString(levelNumber)
end

levelNames = {
    "Test Flight",
    "Just One Ways",
    "Big Gulp",
    "Key Analysis",
    "Hooked",
    "Getaway-Gates",
    "Rod-a-Bout",
    "Luxury Raceway",
    "Hide+See-Key",
    "Turbo Boost!",
    "Grab Grab+Go!",
    "Meditative Test",
    "Criss Crossing",
    "Mind the Curve",
    "Before the Storm",
    "Push+Pull",
    "Fuel Shortage",
    "Lone Station",
    "Tight Squeeze",
    "Caution Cannon",
    "Cannonballers",
    "Team Push+Pull",
    "A-maze-ing",
    "Broadsides",
    "Final Countdown"
}

local levelBgmPaths = {
    "music/SmoothAndCool.mp3",
    "music/StrangeStuff.mp3",
    "music/E1M8.mp3",
    "music/E3M6.mp3",
    "music/scifiNights.mp3",
}

function levelSongPath(_levelNumber)
    local levelNumber = _levelNumber or currentLevel
    if levelNumber == numLevels then
        return "music/the-countdown.mp3"
    end
    print("music for level ", levelNumber, #levelBgmPaths, luaMod(levelNumber,#levelBgmPaths+1))
    return levelBgmPaths[luaMod(levelNumber,#levelBgmPaths+1)]
end
