---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 07/08/2022 22:52
---
local file <const> = playdate.file
numLevels = 0
while file.exists(levelPath(numLevels+1) .. ".pdz") do numLevels = numLevels + 1 end
if numLevels == 0 then
    error("no levels")
end

--- returns challenge index in [challenges] to attempt next. Returns nil if all challenges were achieved
function firstUnCompletedChallenge(levelNum)
    local levelRecords = records[levelNum]
    printTable(levelRecords)
    if not levelRecords then
        return 1 -- first challenge
    end
    local challenges = getChallengesForPath(levelPath(levelNum))
    for challengeIdx, score in ipairs(challenges) do
        if levelRecords[challengeIdx] > score then
            print("found challenge", score, levelRecords[challengeIdx])
            -- challenge not completed
            return challengeIdx
        end
    end

    -- this code is probably only reached when the player has completed the game
    return nil
end

--- returns level number, challenge
function nextUnfinishedLevel()
    local unlockedIdx = numLevelsUnlocked()
    if unlockedIdx <= numLevels then
        local nextChallenge = firstUnCompletedChallenge(unlockedIdx)
        if nextChallenge then
            return unlockedIdx, nextChallenge
        end
    end

    for i = 1, numLevels do
        local nextChallenge = firstUnCompletedChallenge(i)
        if nextChallenge then
            return i, nextChallenge
        end
    end

    -- all levels unlocked and no remaining challenges
    return 1,1
end
