---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 25/08/2022 22:40
---

import "CoreLibs/object"

class("MusicManager").extends()

function MusicManager:init()
    MusicManager.super.init()
    self.volume = 1.0
    self.currentPath = nil
    self.player = nil
end

if not musicManager then
    musicManager = MusicManager()
end

function MusicManager:play(path)
    print("---MUSIC", path)
    if self.currentPath == path and self.player and self.player:isPlaying() then
        print("Already playing this track.")
        return
    end
    sample("loading new track", function()
        self:stop()
        self.player = playdate.sound.fileplayer.new(path)
        if self.player then
            self.player:setStopOnUnderrun(false)
            self.player:setVolume(self.volume)
            self.player:play()
            self.currentPath = path
        end
    end, 1)
    print("---END MUSIC")
end

function MusicManager:stop()
    if self.player then
        self.player:stop()
        self.player = nil
        self.currentPath = nil
    end
end

-- range 0.0 - 1.0
function MusicManager:setVolume(vol)
    self.volume = vol
    if self.player then
        self.player:setVolume(vol)
    end
end
