---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 17/04/2022 16:49
---

--- A State that provides an update function

import "CoreLibs/object"

class("Screen").extends()

function Screen:update()
    -- no-op, implemented in subclasses
end

function Screen:debugDraw()
    -- no-op, implemented in subclasses
end
