---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 17/04/2022 17:10
---

import "CoreLibs/object"
import "screen.lua"

class("StartScreen").extends(Screen)
