---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 01/04/2022 18:12
---

local menu <const> = playdate.getSystemMenu()
local gfx <const> = playdate.graphics

local function onBackgroundChange(newBG)
    printf("Changing background to ", newBG)
    if newBG == "white" then
        gameBgColor = gfx.kColorWhite
    elseif newBG == "win95" then
        gameBgColor = gfx.kColorClear
    else
        gameBgColor = gfx.kColorBlack
    end
    bricksView = BricksView()
end

local function onLevelChange(newLevelNumber)
    currentLevel = tonumber(newLevelNumber)
    InitGame("levels/LEVEL".. newLevelNumber .. ".pdz")
end

local function onDebugChange(newDebugValue)
    Debug = newDebugValue
end

menu:addOptionsMenuItem("BG", {"black","white", "win95"}, "black", onBackgroundChange)
menu:addOptionsMenuItem("level", {"01","02","03","04","05","06","07","08", "09", "10"}, "03", onLevelChange)
menu:addCheckmarkMenuItem("debug", Debug, onDebugChange)
