---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 05/08/2022 11:15
---

import "util.lua"

local function test(expected, actual, description)
    print(description)
    if expected ~= actual then
        error(string.format("Expected %s, got %s", expected, actual))
    end
end

print "----TESTS"

test(0, roundToNearest(0,2), "roundToNearest(0,2)")
test(2, roundToNearest(1.2,2), "roundToNearest(1.2,2)")
test(2, roundToNearest(2,2), "roundToNearest(2,2)")
test(2, roundToNearest(2.1,2), "roundToNearest(2.1,2)")
test(4, roundToNearest(3,2), "roundToNearest(3,2)")
test(4, roundToNearest(3.1,2), "roundToNearest(3.1,2)")
test(-2, roundToNearest(-1.2,2), "roundToNearest(1.2,2)")
test(-2, roundToNearest(-2,2), "roundToNearest(2,2)")
test(-2, roundToNearest(-2.1,2), "roundToNearest(2.1,2)")
test(-2, roundToNearest(-3,2), "roundToNearest(3,2)")
test(-4, roundToNearest(-3.1,2), "roundToNearest(3.1,2)")


print "----TESTS OK"
