---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 30/04/2022 16:54
---

--- Achievement targets.
--- key = file path
--- value = {completion time, fuel spent, lives lost}
challenges = {
    ["levels/LEVEL01.pdz"] = {235, 1200, 1},
    ["levels/LEVEL02.pdz"] = {98, 1200, 10},
    ["levels/LEVEL03.pdz"] = {98, 1200, 1},
    ["levels/LEVEL04.pdz"] = {98, 1200, 1},
    ["levels/LEVEL05.pdz"] = {98, 1200, 1},
    ["levels/LEVEL06.pdz"] = {98, 1200, 1},
    ["levels/LEVEL07.pdz"] = {98, 1200, 1},
    ["levels/LEVEL08.pdz"] = {98, 1200, 1},
    ["levels/LEVEL09.pdz"] = {98, 1200, 1},
    ["levels/LEVEL10.pdz"] = {98, 1200, 1},
}
