---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 30/04/2022 16:54
---
--- Achievement targets.
--- key = file path
--- value = {completion time, fuel spent, lives lost}
--- achievements are unlocked / completed when the user achieves a lower record, ie.
--- when the challenge is fuel 1200; the achievement is awarded when the user completes the level
--- with 1199 or less spent fuel

numChallenges = 3

local defaultChallenges = {235, 1200, 1}

local challenges = {
    ["levels/LEVEL01"] = {235, 1200, 1},
    ["levels/LEVEL02"] = {98, 1200, 10},
    ["levels/LEVEL03"] = {98, 1200, 1},
    ["levels/LEVEL04"] = {98, 1200, 1},
    ["levels/LEVEL05"] = {98, 1200, 1},
    ["levels/LEVEL06"] = {98, 1200, 1},
    ["levels/LEVEL07"] = {98, 1200, 1},
    ["levels/LEVEL08"] = {98, 1200, 1},
    ["levels/LEVEL09"] = {98, 1200, 1},
    ["levels/LEVEL10"] = {98, 1200, 1},
}


function getChallengeForPath(path)
    return challenges[path] or defaultChallenges
end
