---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 29/04/2022 11:20
---

local numChallenges <const> = numChallenges
local levelNames <const> = levelNames
local pressed <const> = playdate.buttonIsPressed
local justPressed <const> = playdate.buttonJustPressed
local justReleased <const> = playdate.buttonJustReleased
local buttonDown <const> = playdate.kButtonDown
local buttonUp <const> = playdate.kButtonUp
local buttonLeft <const> = playdate.kButtonLeft
local buttonRight <const> = playdate.kButtonRight
local buttonA <const> = playdate.kButtonA
local buttonB <const> = playdate.kButtonB

local ceil <const> = math.ceil

class("LevelSelectViewModel").extends()

function LevelSelectViewModel:init()
    LevelSelectViewModel.super.init(self)
    self.lastUnlocked = numLevelsUnlocked()
    --- the level for which an unlock animation should be played
    self.newUnlock = nil
    self.menuOptions = {}
    for i = 1,numLevels do
        self.menuOptions[i] = {
            title = levelNames[i],
            challenges = getChallengesForPath(levelPath(i)),
            levelNumber = i,
            -- scores added on resume
        }
    end
    self.selectedIdx = numLevelsUnlocked()
    self.selectedChallengeIdx = firstUnCompletedChallenge(self.selectedIdx) or 1
    self.dPadImageIdx = 1
    self.aButtonImageIdx = 1
end

function LevelSelectViewModel:resume()
    local numLevelsUnlocked = numLevelsUnlocked()
    print("numLevelsUnlocked", numLevelsUnlocked)
    if self.lastUnlocked ~= numLevelsUnlocked then
        self.lastUnlocked = numLevelsUnlocked
        self.newUnlock = numLevelsUnlocked
    end
    for i = 1,numLevels do
        local curOptions = self.menuOptions[i]
        local rawScores = records[i]
        local achievements = {}
        if rawScores then
            -- formatting for display
            curOptions.scores = {
                ceil(rawScores[1]),
                ceil(rawScores[2]),
                rawScores[3]
            }
            for j, score in ipairs(rawScores) do
                achievements[j] = score <= curOptions.challenges[j]
            end
        end
        curOptions.achievements = achievements
        curOptions.unlocked = numLevelsUnlocked >= i
    end
    --- when pressing the A button to dismiss a gameOverScreen, we don't want to register that press
    --- here again to start a level
    self.aButtonPressedAtLeastOnce = false
end

function LevelSelectViewModel:pause()
    self.newUnlock = nil
end

function LevelSelectViewModel:finish()
    if self.keyTimer then
        self.keyTimer:remove()
    end
    popScreen()
end

--- returns true when finished
function LevelSelectViewModel:update()
    if justPressed(buttonDown) then
        local function timerCallback()
            if self.selectedIdx < #self.menuOptions and (numLevelsUnlocked() >= self.selectedIdx + 1 or Debug) then
                self.selectedIdx = self.selectedIdx + 1
                self.selectedChallengeIdx = firstUnCompletedChallenge(self.selectedIdx) or 1
            end
        end
        self.keyTimer = playdate.timer.keyRepeatTimer(timerCallback)
    elseif justPressed(buttonUp) then
        local function timerCallback()
            if self.selectedIdx > 1 then
                self.selectedIdx = self.selectedIdx - 1
                self.selectedChallengeIdx = firstUnCompletedChallenge(self.selectedIdx) or 1
            end
        end
        self.keyTimer = playdate.timer.keyRepeatTimer(timerCallback)
    elseif justReleased(buttonDown | buttonUp) then
        if self.keyTimer then
            self.keyTimer:remove()
        end
    elseif justPressed(buttonLeft) then
        self.selectedChallengeIdx = clamp(self.selectedChallengeIdx -1, 1, numChallenges)
    elseif justPressed(buttonRight) then
        self.selectedChallengeIdx = clamp(self.selectedChallengeIdx +1, 1, numChallenges)
    elseif justPressed(buttonA) then
        self.aButtonPressedAtLeastOnce = true
    elseif justReleased(buttonA) and self.aButtonPressedAtLeastOnce then
        ui_confirm:play()
        currentLevel = self.selectedIdx
        require("lua/gameScreen")

        -- start orientation video
        if self.selectedIdx == 1 then
            require "lua/video-player/VideoPlayerScreen"
            pushScreen(VideoPlayerScreen(
                "video/orientation",
                function()
                    return GameScreen(currentLevel, self.selectedChallengeIdx)
                end
            ))
        else
            pushScreen(
                GameScreen(currentLevel, self.selectedChallengeIdx)
            )
        end
    elseif justPressed(buttonB) then
        ui_cancel:play()
        self:finish()
    end

    self.aButtonImageIdx = pressed(buttonA) and 2 or 1
    self.dPadImageIdx = pressed(buttonLeft) and 2 or pressed(buttonRight) and 3 or 1
end

function LevelSelectViewModel:selectedOption()
    return self.menuOptions[self.selectedIdx]
end
