---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 29/04/2022 11:20
---

import "CoreLibs/object"
import "CoreLibs/timer"
import "../util.lua"
import "challenges.lua"


local keyTimer = nil
local pressed <const> = playdate.buttonIsPressed
local justPressed <const> = playdate.buttonJustPressed
local justReleased <const> = playdate.buttonJustReleased
local buttonDown <const> = playdate.kButtonDown
local buttonUp <const> = playdate.kButtonUp
local buttonA <const> = playdate.kButtonA
local buttonB <const> = playdate.kButtonB

-- Select the first challenge that was not completed
local function getDefaultChallenge(self)
    local selectedChallenges = self:selectedOption().challenges
    local selectedRecords = records[levelPath(self.selectedIdx)]
    if not selectedChallenges or not selectedRecords then
        self.selectedChallenge = 1
        return 1
    end

    inspect(selectedChallenges) inspect(selectedRecords)

    for i, challenge in ipairs(selectedChallenges) do
        if challenge < selectedRecords[i] then -- the challenge was not beat
            return i
        end
    end

    return 1
end

class("LevelSelectViewModel").extends()

function LevelSelectViewModel:init()
    self.menuOptions = {}
    for i = 1,10 do
        self.menuOptions[i] = {
            title = "Stage " .. levelNumString(i),
            challenges = challenges[levelPath(i)],
            -- may be nil if level was not completed before
            scores = records[levelPath(i)] -- fastest completion time, fuel spent, lives lost
        }
    end
    self.selectedIdx = 1
    self.selectedChallenge = getDefaultChallenge(self)
end

function LevelSelectViewModel:update()
    if justPressed(buttonDown) then
        local function timerCallback()
            if self.selectedIdx < #self.menuOptions then
                self.selectedIdx = self.selectedIdx + 1
                self.selectedChallenge = getDefaultChallenge(self)
            end
        end
        keyTimer = playdate.timer.keyRepeatTimer(timerCallback)
    elseif justPressed(buttonUp) then
        local function timerCallback()
            if self.selectedIdx > 1 then
                self.selectedIdx = self.selectedIdx - 1
                self.selectedChallenge = getDefaultChallenge(self)
            end
        end
        keyTimer = playdate.timer.keyRepeatTimer(timerCallback)
    elseif justReleased(buttonDown | buttonUp) then
        keyTimer:remove()
    end
end

function LevelSelectViewModel:selectedOption()
    return self.menuOptions[self.selectedIdx]
end
