---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 24/04/2022 22:29
---

import "levelSelectView"
import "levelSelectViewModel"

class("LevelSelectScreen").extends(Screen)

local levelSelectView, levelSelectViewModel

function LevelSelectScreen:init()
    LevelSelectScreen.super.init(self)
    levelSelectViewModel = LevelSelectViewModel()
    levelSelectView = LevelSelectView(levelSelectViewModel)
end

function LevelSelectScreen:pause()
    levelSelectViewModel:pause()
end

function LevelSelectScreen:resume()
    levelSelectViewModel:resume()
    levelSelectView:resume()
end

function LevelSelectScreen:gameWillPause()
    levelSelectViewModel:gameWillPause()
end

function LevelSelectScreen:destroy()
    levelSelectViewModel:destroy()
end

function LevelSelectScreen:update()
    levelSelectViewModel:update()
    levelSelectView:render(levelSelectViewModel)
end
