---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 24/04/2022 22:42
---

import "CoreLibs/object"
import "CoreLibs/ui"

local gfx <const> = playdate.graphics

local listRect = playdate.geometry.rect.new(220, 20, 160, 210)
local listView = playdate.ui.gridview.new(0, 10)
listView:setCellPadding(0, 0, 13, 10)
listView:setContentInset(24, 24, 13, 11)

class("LevelSelectView").extends()
local menuOptions

function listView:drawCell(section, row, column, selected, x, y, width, height)
    gfx.fillRoundRect(100, 100, 50, 50, 4) -- test rect for debugging

    if selected then
        gfx.fillRoundRect(x, y, width, 20, 4)
        gfx.setImageDrawMode(gfx.kDrawModeFillWhite)
    else
        gfx.setImageDrawMode(gfx.kDrawModeCopy)
    end
    gfx.drawTextInRect(menuOptions[row], x, y+2, width, 100, nil, "...", kTextAlignment.center)
end

function LevelSelectView:init(viewModel)
    menuOptions = viewModel.menuOptions
    listView:setNumberOfRows(#menuOptions)
end

function LevelSelectView:render(viewModel)
    if listView:getSelectedRow() ~= viewModel.selectedRow then
        -- if we always set the selectedRow, it will be marked dirty on every frame
        listView:setSelectedRow(viewModel.selectedRow)
        listView:scrollToRow(viewModel.selectedRow)
    end

    if listView.needsDisplay then
        gfx.setClipRect(listRect)
        gfx.clear(gfx.kColorWhite)
        listView:drawInRect(listRect.x, listRect.y, listRect.width, listRect.height)
    end

end
