---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 10/07/2022 17:34
---

import "CoreLibs/object"

class('Input').extends()

function Input:init()
    Input.super.init()
end

function Input:isInputPressed(action)
    return false
end

function Input:isInputJustPressed(action)
    return false
end
