---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 10/07/2022 17:34
---

class('Input').extends()

-- Values must be powers of 2 for bitmasking purposes
Input.actionNone = 0
Input.actionLeft = 1
Input.actionRight = 2
Input.actionThrottle = 4
Input.actionSelfRight = 8

function Input:init()
    Input.super.init(self)
end

function Input:isInputPressed(action)
    return false
end

function Input:resetRotationTimeout() end

--- returns new rotation given current rotation, or nil if no change
function Input:rotationInput(currentRotation)
    return nil
end

function Input:isInputJustPressed(action)
    return false
end
