---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 12/03/2022 16:10
---

local gfx = playdate.graphics

function pgeDrawLine(x1, y1, x2, y2, color)
    gfx.setColor(color)
    gfx.drawLine(x1, y1, x2, y2)
end

function pgeDrawRect(x, y, w, h, color)
    gfx.setColor(color)
    gfx.fillRect(x, y, w, h)
end

function pgeDrawText(x, y, color, text)
    gfx.drawText(text, x, y)
end
