---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 12/03/2022 16:10
---

local graphics = playdate.graphics

function pgeDraw(x, y, width, height, texstartx, texstarty, texW, texH, rotation, alpha)
    printf("WARNING rotation and alpha ignored")
    pgeDraw(x, y, width, height, texstartx, texstarty, texW, texH)
end

function pgeDraw(x, y, width, height, texstartx, texstarty, texW, texH)
    if width ~= texW or height ~= texH then
        printf("WARNING ignoring scaling")
    end
    sprite:draw(x, y, graphics.kImageUnflipped, texstartx, texstarty, texW, texH)
end
