---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 13/03/2022 00:13
---

local pressed = playdate.buttonIsPressed

function ProcessInputs()
    -- thrust
    if pressed("a") or pressed("b") or pressed("up") then
        if fuel>0 then
            thrust = 1
            fuel = fuel - burnRate
            if not flying then
                vx = 0
                vy = 0
            end
            flying = true
            vx = vx + math.cos(-planeRot/12*pi)*(thrustPower+extras[1]*turboPower)
            vy = vy - math.sin(-planeRot/12*pi)*(thrustPower+extras[1]*turboPower)
            if Sounds and not thrust_sound:isPlaying() then thrust_sound:play(0) end
        else
            thrust = 0
        end
    else
        thrust = 0
        if Sounds then thrust_sound:stop() end
    end

    -- rotation
    if pressed("down") then
        if planeRot~=18 then
            if planeRot>18 or planeRot<6 then
                planeRot = planeRot-1
            else
                planeRot = planeRot+1
            end
        end
        if planeRot<0 then planeRot = 23 end
    elseif pressed("left") then
        if flying then
            planeRot = planeRot - 1
            if planeRot<0 then
                planeRot = 23
            end
        end
    elseif pressed("right") then
        if flying then
            planeRot = planeRot + 1
            planeRot = planeRot % 24

        end
    end
end
