---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 01/04/2022 18:12
---

local menu <const> = playdate.getSystemMenu()
local gfx <const> = playdate.graphics

local function onFrameRateChange(newFramerate)
    printf("Changing framerate to ", newFramerate)
    playdate.display.setRefreshRate(newFramerate)
end

local function onLevelChange(newLevelNumber)
    InitGame("levels/LEVEL".. newLevelNumber .. ".pdz")
end

local function onDitherChange(newDitherName)
    sprite = gfx.image.new("images/sprite_" .. newDitherName .. ".png") -- https://www.gingerbeardman.com/canvas-dither/
    if not sprite then error("failed to load sprite") end
    bricksView = BricksView()
end

menu:addOptionsMenuItem("fps", {"0","20","30"}, "30", onFrameRateChange)
menu:addOptionsMenuItem("level", {"01","02","03","04","05","06","07","08", "09", "10"}, "03", onLevelChange)
menu:addOptionsMenuItem("dither", {"atkinson", "stucki", "burkes"}, "atkinson", onDitherChange)
