---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 17/04/2022 21:28
---
import "CoreLibs/object"

class("StartViewState").extends()

function StartViewState:init()
    self.startGameProgress = 0
end
