---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 17/04/2022 17:10
---

import "CoreLibs/object"
import "../screen.lua"
import "startView.lua"
import "startViewModel.lua"

class("StartScreen").extends(Screen)

local renderStart <const> = RenderStart

function StartScreen:init(planeX, planeY)
    StartScreen.super.init(self)
    self.initialPlaneX = planeX
    self.initialPlaneY = planeY
end

function StartScreen:update()
    renderStart(self.viewModel:calcTimeStep())
end

function StartScreen:pause()
    self.viewModel:pause()
end

function StartScreen:resume()
    -- reset state entirely
    self.viewModel = StartViewModel(self.initialPlaneX, self.initialPlaneY)
end
